config/routes.rb
Rails.application.routes.draw do

  resources :sessions 
  # Semi-static page routes
   get 'home', to: 'home#index', as: :home
   get 'home/about', to: 'home#about', as: :about
   get 'home/contact', to: 'home#contact', as: :contact
   get 'home/privacy', to: 'home#privacy', as: :privacy
   get 'search', to: 'search#search', as: :search
 
   resources :users, only: [:edit, :index, :new, :create, :update]
   get 'users/new', to: 'users#new', as: :signup
   get 'user/edit', to: 'users#edit', as: :edit_current_user
   get 'login', to: 'sessions#new', as: :login
   get 'logout', to: 'sessions#destroy', as: :logout
 
   resources :categories
   resources :items, except: [:index] # in the future, items should be destroyed if there are no submissions attached

   resources :case_workers
   
   # access assignments and submissions for a given parent
   resources :parents do
    resources :assignments do
      resources :submissions
    end
   end

   resources :assignments
   resources :submissions

   #get 'parents/:id/assignments', to: 'assignment#index', as: :parent_assignments
   #get 'parents/:id/assignments/:a_id', to: 'assignment#show', as: :parent_assignment
   get 'items/:id/parent_show', to: 'items#parent_show', as: 'parent_show'
   get 'categories/:id/item_show', to: 'categories#item_show', as: :item_show

   patch 'categories/:id/toggle_active_category', to: 'categories#toggle_active_category', as: :toggle_active_category
   patch 'items/:id/toggle_active_item', to: 'items#toggle_active_item', as: :toggle_active_item
   patch 'parents/:id/toggle_active_parent', to: 'parents#toggle_active_parent', as: :toggle_active_parent

   root 'home#index'

  # Hello For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/partials/_add_new_object.html.erb
<!-- Add a button for new instances of object -->
<%  if can? :new, eval(model_name.capitalize) && controller.respond_to?(:new) %>
  <%= link_to(eval("new_#{model_name}_path"), class: "waves-effect waves-light btn") do %>
    &nbsp;Add a New <%= model_name.capitalize %>
  <% end %>
<% end %>

app/views/partials/_display_base_errors.html.erb
<% unless object.errors.empty? %>
  <div data-alert data-options="animation_speed:500, animation:'fadeOut';" class="alert-box warning">
    <%= object.errors[:base].first %>
  </div>
<% end %>

app/views/partials/_flash.html.erb
<% flash.each do |name, msg| %>
  <div id="flash_box" data-alert data-options="animation_speed:500, animation:'fadeOut';" class="alert-box <%= flash[:notice] ? "success" : "warning" %>">
    <!-- <a href="#" class="close">&times;</a> -->
      <%= msg %>
  </div>
<% end %>

app/views/partials/_footer.html.erb
<p class="supertiny">&nbsp;</p>

<div id="footer" class="center-align">
  
  <%= link_to 'Home', home_path %>&nbsp;&nbsp;::&nbsp;&nbsp;
  <%= link_to 'About', about_path %>&nbsp;&nbsp;::&nbsp;&nbsp;
  <%= link_to 'Contact', contact_path %>&nbsp;&nbsp;::&nbsp;&nbsp;
  <%= link_to 'Privacy', privacy_path %>
  <br />
  <div id="copy">
    Webmaster: <%= mail_to("junn@andrew.cmu.edu", "GVCS 67-373 Team", encode: "javascript") %> 
    &nbsp;&nbsp;&copy 2023
  </div>

</div>

app/views/partials/_form2_structure.html.erb
<%# FOR NESTED FORMS; 2 SETS OF FIELDS %>
<div class="row">
  <div class="col s9">
    <div class="card">    
      <div class="card-content">
        <span class="card-title"><%= type_of_form %></span>
        <%= simple_form_for(object) do |f| %>
          <%= f.error_notification %>
          <div class="row">
            <div class="form-inputs">
              <%# First set of fields for main object %>
              <%= render partial: "#{fields1}", locals: { f: f } %>
            </div>
          </div>
          <div class="row">
            <div class="col s12">
              <div class="card grey lighten-3">
                <div class="row">
                  <div class="card-content">
                    <%# Second set of fields and title for nested object %>
                    <span class="card-title"><%= section_2 %></span>
                    <div class="form-inputs">
                      <%= render partial: "#{fields2}", locals: { f: f } %>
                    </div>
                  </div>
                </div>    
              </div>              
            </div>
          </div>
          <p>&nbsp;</p>
          <div class="row">
            <div class="form-actions col s9">
              <%= f.button :submit %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>
<%= link_to 'Back', :back %>

app/views/partials/_form_structure.html.erb
<div class="row">
  <div class="col s9">
    <div class="card">    
      <div class="card-content">
        <span class="card-title"><%= type_of_form %></span>
        <%= simple_form_for(object) do |f| %>
          <%= f.error_notification %>
          <div class="row">
            <div class="form-inputs">
              <%= render partial: "#{fields}", locals: { f: f } %>
            </div>
          </div>
          <p>&nbsp;</p>
          <div class="row">
            <div class="form-actions col s9">
              <%= f.button :submit %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>
<%= link_to 'Back', :back %>

app/views/partials/_index_structure.html.erb
<div class="row">
  <div class="col s7">
    <!-- primary partial gets displayed here in main div -->
    <%= render partial: "#{primary}" %>
    <!-- sometimes we want another partial below -->
    <% unless secondary.nil? %>
      <%# <p>&nbsp;</p> %>
      <%= render partial: "#{secondary}" %>
    <% end %>
    
  </div>
  <%# <div class="col s1">
    <!-- add a spacing column -->
    <p>&nbsp;</p>
  </div> %>
  <div class="col s5">
    <!-- render the sidebar, if it exists -->
    <%= render partial: "#{sidebar}" unless sidebar.blank? %>
  </div>
</div>

<!-- Add a button for new instances of object -->
<%= render :partial => "partials/add_new_object", locals: {model_name: model_name} %>

app/views/partials/_nav_customer.html.erb
<nav id="nav">
  <div class="container">
    <ul class="left hide-on-med-and-down">
        <li><%= link_to 'Home', home_path %></li>
        <li><%= link_to 'My Account', customer_path(current_user.customer) %></li>
        <li><%= link_to 'My Orders', orders_path %></li>
        <li><%= link_to 'Items', items_path %></li>

    </ul>
    <ul class="right">

      <li><%= link_to 'Logout', logout_path %></li>
    </ul>
  </div>
</nav>

app/views/partials/_nav_foster_parent.html.erb
<nav id="nav">
  <div class="container">
    <ul class="left hide-on-med-and-down">
        <li><%= link_to 'Home', home_path %></li>
        <li><%= link_to 'Checklist Categories', categories_path %></li>
        <li><%= link_to "To-Do List (#{@incomplete_assignments.size})", assignments_path %></li>

    </ul>
    <ul class="right">
      <li><%= link_to 'Profile', parent_path(current_user.parent) %></li>
      <li><%= link_to 'Logout', logout_path %></li>
    </ul>
  </div>
</nav>

app/views/partials/_nav_guest.html.erb
<nav id="nav">
  <div class="container">
    <ul class="left hide-on-med-and-down">
        <li><%= link_to 'Home', home_path %></li>
    </ul>

    <ul class="right">
      <li><%= link_to 'Become a Foster Parent', new_parent_path %></li>
      <li><%= link_to 'Login', login_path %></li>
    </ul>
  </div>
</nav>

app/views/partials/_object_options.html.erb
<% opt = "#{object.respond_to?(:name) ? object.name : model_name.capitalize }" %>

<div class="form-actions">
  
  <% if can? :index, eval(model_name.capitalize) && controller.respond_to?(:index) %>
    <%= link_to(eval("#{model_name.pluralize}_path"), class: 'waves-effect waves-light btn') do %>
      &nbsp;Display All <%# model_name.pluralize.capitalize %>
    <% end %>
    &nbsp;&nbsp;
  <% end %>
  
  <% if can? :edit, object %> 
    <%= link_to(eval("edit_#{model_name}_path(object)"), class: 'waves-effect waves-light btn') do %>
        &nbsp;<%= "Edit #{opt}" %>
    <% end %>
    &nbsp;&nbsp;
  <% end %>
  
  <% if can?(:destroy, object) && controller.respond_to?(:destroy) %>
    <%= link_to(eval("#{model_name}_path(object)"), method: 'delete', data: {confirm: "Are you sure you want to permanently delete #{opt}"}, class: 'waves-effect waves-light btn btn-alert') do %>
        &nbsp;<%= "Delete #{opt}" %>
    <% end %>
  <% end %>
</div>

app/views/partials/_show_structure.html.erb
<div class="row">

  <div class="col s7">
      <!-- primary partial gets displayed here in main div -->
      <%= render partial: "#{primary}" %>
      <!-- sometimes we want another partial below -->
      <% unless secondary.nil? %>
        <%= render partial: "#{secondary}" %>
      <% end %>
  </div>

  <div class="col s5">
    <!-- render the sidebar, if it exists -->
    <%= render partial: "#{sidebar}" unless sidebar.blank? %>
  </div>

</div>
<!-- Add base errors and/or buttons for object management -->
<div class="row">
  <%= render :partial => "partials/display_base_errors", locals: {object: object} %>
  <%= render :partial => "partials/object_options", locals: {model_name: model_name, object: object} %>
</div>

app/views/partials/_structure2.html.erb
<div class="row">
  <div class="col s8">
    <!-- primary partial gets displayed here in main div -->
    <%= render partial: "#{primary}" %>
    <!-- sometimes we want another partial below -->
    <% unless secondary.nil? %>
      <p>&nbsp;</p>
      <%= render partial: "#{secondary}" %>
    <% end %>
  </div>
  <div class="col s4">
    <!-- render the sidebar, if it exists -->
    <%= render partial: "#{sidebar}" unless sidebar.blank? %>
  </div>
</div>
<div class="row">
  <%= render :partial => "partials/display_base_errors", locals: {object: object} %>
  <%= render :partial => "partials/object_options", locals: {model_name: model_name, object: object} %>
</div>

app/views/partials/_topbar.html.erb
<div id="topbar_style">
    <h2><%= link_to 'GVCS Submission System', home_path %></h2>
</div>