config/routes.rb
Rails.application.routes.draw do

  resources :sessions 
  # Semi-static page routes
   get 'home', to: 'home#index', as: :home
   get 'home/about', to: 'home#about', as: :about
   get 'home/contact', to: 'home#contact', as: :contact
   get 'home/privacy', to: 'home#privacy', as: :privacy
   get 'search', to: 'search#search', as: :search
 
   resources :users, only: [:edit, :index, :new, :create, :update]
   get 'users/new', to: 'users#new', as: :signup
   get 'user/edit', to: 'users#edit', as: :edit_current_user
   get 'login', to: 'sessions#new', as: :login
   get 'logout', to: 'sessions#destroy', as: :logout
 
   resources :categories
   resources :items, except: [:index] # in the future, items should be destroyed if there are no submissions attached

   resources :case_workers
   
   # access assignments and submissions for a given parent
   resources :parents do
    resources :assignments do
      resources :submissions
    end
   end

   resources :assignments
   resources :submissions

   #get 'parents/:id/assignments', to: 'assignment#index', as: :parent_assignments
   #get 'parents/:id/assignments/:a_id', to: 'assignment#show', as: :parent_assignment
   get 'items/:id/parent_show', to: 'items#parent_show', as: 'parent_show'
   get 'categories/:id/item_show', to: 'categories#item_show', as: :item_show

   patch 'categories/:id/toggle_active_category', to: 'categories#toggle_active_category', as: :toggle_active_category
   patch 'items/:id/toggle_active_item', to: 'items#toggle_active_item', as: :toggle_active_item
   patch 'parents/:id/toggle_active_parent', to: 'parents#toggle_active_parent', as: :toggle_active_parent

   root 'home#index'

  # Hello For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/item.rb
class Item < ApplicationRecord
  # Modules to help with some functionality
  include AppHelpers::Validations
  include AppHelpers::Activeable::InstanceMethods
  extend AppHelpers::Activeable::ClassMethods


  belongs_to :category
  has_many :submissions
  has_many :assignments
  has_one_attached :file

  # Scopes
  scope :alphabetical, -> { order(:name) }
  scope :for_category, ->(category) { where(category_id: category.id) }
  scope :search,       ->(term) { where('name LIKE ? OR description LIKE ?', "%#{term}%", "%#{term}%") }


  validates :name, presence: true, uniqueness: { case_sensitive: false }
  validate :category_is_active_in_the_system, on: :create
  validates :due_date, presence: true

  private
    def category_is_active_in_the_system
      is_active_in_system(:category)
    end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
    before_action :set_item, only: [:show, :edit, :update, :toggle_active_item, :destroy]
    before_action :check_login, only: [:show, :edit, :update, :destroy]
    authorize_resource
  
    def new
      @item = Item.new
    end
  
    def create
      @item = Item.new(item_params)
  
      if @item.save
        flash[:notice] = "#{@item.name} was added to the system."
        redirect_to category_path(@item.category)
      else
        render action: 'new'
      end
    end
  
    def edit
    end
  
    def show
      if current_user.role?(:parent)
        @parent = current_user.parent
        # all assignments that have been assigned to the user
        @assignments = Assignment.for_parent(current_user.parent.id).paginate(page: params[:page]).per_page(15)
        
        @item = Item.find(params[:id])
        parent_assignments = @assignments.select { |assignment| assignment.item == @item }
        @submissions = parent_assignments.map(&:submission).compact
      end   
    end

    def parent_show
      if current_user.role?(:case_worker)
        # all assignments that have been assigned to the particular parent that I'm looking at
        @item = Item.find(params[:id])
        @parent = Parent.find(params[:parent_id])
        @assignments = Assignment.where(item: @item, parent: @parent)
        
        @submissions = Submission.joins(:assignment)
                         .where(assignments: { id: @assignments.pluck(:id) })
                         .chronological
      end
    end
  
    def update
      if @item.update_attributes(item_params)
        flash[:notice] = "Successfully updated #{@item.name}."
        redirect_to item_path
      else
        render action: 'edit'
      end
    end

    def destroy
      @item = Item.find(params[:id])
      @submission = @item.assignment.submission
      @category = @item.category
    
      begin
        @item.destroy!
        flash[:success] = 'Item was successfully deleted.'
        redirect_to category_path(@category)
      rescue ActiveRecord::InvalidForeignKey => e
        flash[:error] = 'Cannot delete this Item: there are associated Assignments or Submissions.'
        redirect_to item_path(@item)
      end
    end

    def toggle_active_item
      if @item.active
        @item.update_attribute(:active, false)
        @item.save

        flash[:notice] = "#{@item.name} was made inactive"
        redirect_to item_path(@item)
      else
        @item.update_attribute(:active, true)
        @item.save

        flash[:notice] = "#{@item.name} was made active"
        redirect_to item_path(@item)
      end
  end
  
    private
      def set_item
        @item = Item.find(params[:id])
      end
  
      def item_params
        params.require(:item).permit(:name, :instructions, :filename, :file, :due_date, :active, :category_id)
      end
  
  end
  

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_completion_status.html.erb
<div class="card">
    <div class="card-content">

        <% there_is_incomplete = @assignments.any? { |assignment| assignment.item == @item && !assignment.completion }%>
        
        <% if there_is_incomplete %>
            <div class = "completion_column_container">
                <div class = "completion_column">
                    <h4>Status </h4>
                    <h4 style="color: #f04735">Incomplete</h4>
                </div>
                <div class = "completion_column">
                    <% @incomplete_assignment = @assignments.find { |assignment| assignment.item == @item && !assignment.completion } %>
                    <h4>Due Date</h4>
                    <h4 style="color: black"><%= "#{@incomplete_assignment.due_date.strftime("%m/%d/%y")}" %></h4>
                </div>
            </div>
        <% else %>
            <h4>Status</h4>
            <h4 style="color: #518458">Complete</h4>
        <% end %>

    </div>
</div>

<% if there_is_incomplete%>
    <% if can?(:destroy, @incomplete_assignment) && controller.respond_to?(:destroy) %>
        <%= link_to(eval("assignment_path(@incomplete_assignment)"), method: 'delete', data: {confirm: "Are you sure you want to permanently delete Assignment?"}, class: 'waves-effect waves-light btn btn-alert') do %>
            &nbsp;<%= "Delete Assignment" %>
        <% end %>
    <% end %>
<% end %>

app/views/items/_file_data.html.erb
<div class="card">
    <div class="card-content">
        <h4><%= @item.name %> </h4>

        <% if @item.active %>
            <b>Status: </b>Active Item<br><br>
        <% else %>
            <b>Status: </b>Inactive Item<br><br>
        <% end %>

        <b>Checklist Category:</b> <%= @item.category.name %><br><br>

        <b>Instructions:</b> <%= @item.instructions %><br><br>

        <b>Due Date:</b> <%= @item.due_date %><br><br>

        <% if !@item.nil? && !@item.file.nil? %>
            <b>File:</b> <%= link_to "#{@item.filename}", rails_blob_path(@item.file, disposition: "attachment") %> <br><br>
        <% else %>
            <b>File:</b> No linked files. <br><br>
        <% end %>
        
        

        <% if !current_user.nil? && current_user.role?(:case_worker) %>
            <% if @item.active %>
                <%= link_to "Make Inactive", toggle_active_item_path, method: :patch, class: 'waves-effect waves-light btn btn-alert'%>
            <% else %>
                <%= link_to "Make Active", toggle_active_item_path, method: :patch, class: 'waves-effect waves-light btn btn-alert'%>
            <% end %>
        <% end%>

    </div>
</div>

app/views/items/_item_fields.html.erb
<%= f.input :name, label_html: { class: 'active' } %>
<%= f.input :category_id, collection: Category.active.alphabetical, include_blank: false %>
<%= f.input :instructions, label_html: { class: 'active' } %>
<%= f.input :filename, label_html: { class: 'active' } %>
<%= f.input :file, label_html: { class: 'active' } %>
<%= f.input :due_date, label_html: { class: 'active' } %>

app/views/items/_recent_submissions.html.erb
<div class="card">
    <div class="card-content">
        <% if !current_user.nil? && current_user.role?(:parent) %>
            <h4><%= "#{@item.name} Recent Submissions"%></h4>
        <% else %>
            <h4><%= "#{@item.name} Recent Submissions by #{@parent.p1_last_name}, #{@parent.p1_first_name}"%></h4>
        <% end %>
        
        <table class = "striped highlight">

            <% if @submissions.empty? %>
                <p>There are no submissions for this item.</p>
            <% else %>
                <thead>
                    <th>Date Completed</th>
                    <th>File</th>
                </thead>
                <% for submission in @submissions %>
                <tr>
                    <td><%= link_to "#{submission.date_completed.strftime("%m/%d/%y")}", submission_path(submission) %></td>
                    <% if !submission.nil? && !submission.file.nil? %>
                        <td> <%= link_to "#{submission.filename}", rails_blob_path(submission.file, disposition: "attachment") %> </td>
                    <% else %>
                        <td>No linked files.</td> 
                    <% end %>

                    <% if !current_user.nil? && can?(:destroy, submission) && submission%>
                        <td class="align_center">
                        <%= link_to(submission_path(submission), method: :delete, data: { confirm: 'Are you sure you wish to delete this information?' }) do %>
                            <i class="material-icons">delete</i>
                        <% end %>
                        </td>
                    <% end %>

                </tr>
                <% end%>
            <% end %>

        </table><br>

        

        
        <% if @assignments.any? { |assignment| assignment.item == @item && !assignment.completion }%>
            <% if !current_user.nil? && current_user.role?(:case_worker) %>
                <%= link_to "Add a New Submission", new_submission_path(item_id: @item.id, parent_id: @parent.id), class: 'waves-effect waves-light btn btn-alert' %>
            <% elsif !current_user.nil? && current_user.role?(:parent) %>
                <%= link_to "Add a New Submission", new_submission_path(item_id: @item.id, parent_id: @current_user.parent.id), class: 'waves-effect waves-light btn btn-alert' %>
            <% end %>
        <% end %>

        
        
    </div>
</div>

app/views/items/edit.html.erb
<%= render partial: "partials/form_structure", locals: {object: @item, 
                                                        type_of_form: "Edit Item",
                                                        fields: "item_fields"} %>

app/views/items/new.html.erb
<%= render partial: "partials/form_structure", locals: {object: @item,
                                                        type_of_form: "New Item",
                                                        fields: "item_fields"} %>

app/views/items/parent_show.html.erb
<% if !current_user.nil? && current_user.role?(:case_worker) %>
    <%= render partial: "partials/show3_structure", locals: {model_name: "item", 
                                                            object: @item,
                                                            primary: "recent_submissions", 
                                                            secondary: nil,
                                                            sidebar: "completion_status"} %>
<% end %>

app/views/items/show.html.erb
<% if !current_user.nil? && current_user.role?(:case_worker) %>
    <%= render partial: "partials/show_structure", locals: {model_name: "item", 
                                                            object: @item,
                                                            primary: "file_data", 
                                                            secondary: nil,
                                                            sidebar: nil} %>
<% elsif !current_user.nil? && current_user.role?(:parent) %>
    <%= render partial: "partials/show_structure", locals: {model_name: "item", 
                                                            object: @item,
                                                            primary: "file_data", 
                                                            secondary: "completion_status",
                                                            sidebar: "recent_submissions"} %>
<% end %>