config/routes.rb
Rails.application.routes.draw do

  resources :sessions 
  # Semi-static page routes
   get 'home', to: 'home#index', as: :home
   get 'home/about', to: 'home#about', as: :about
   get 'home/contact', to: 'home#contact', as: :contact
   get 'home/privacy', to: 'home#privacy', as: :privacy
   get 'search', to: 'search#search', as: :search
 
   resources :users, only: [:edit, :index, :new, :create, :update]
   get 'users/new', to: 'users#new', as: :signup
   get 'user/edit', to: 'users#edit', as: :edit_current_user
   get 'login', to: 'sessions#new', as: :login
   get 'logout', to: 'sessions#destroy', as: :logout
 
   resources :categories
   resources :items, except: [:index] # in the future, items should be destroyed if there are no submissions attached

   resources :case_workers
   
   # access assignments and submissions for a given parent
   resources :parents do
    resources :assignments do
      resources :submissions
    end
   end

   resources :assignments
   resources :submissions

   #get 'parents/:id/assignments', to: 'assignment#index', as: :parent_assignments
   #get 'parents/:id/assignments/:a_id', to: 'assignment#show', as: :parent_assignment
   get 'items/:id/parent_show', to: 'items#parent_show', as: 'parent_show'
   get 'categories/:id/item_show', to: 'categories#item_show', as: :item_show

   patch 'categories/:id/toggle_active_category', to: 'categories#toggle_active_category', as: :toggle_active_category
   patch 'items/:id/toggle_active_item', to: 'items#toggle_active_item', as: :toggle_active_item
   patch 'parents/:id/toggle_active_parent', to: 'parents#toggle_active_parent', as: :toggle_active_parent

   root 'home#index'

  # Hello For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/parent.rb
class Parent < ApplicationRecord
  include AppHelpers::Deletions
  include AppHelpers::Validations
  include AppHelpers::Activeable::InstanceMethods
  extend AppHelpers::Activeable::ClassMethods

  attr_accessor :username, :password, :password_confirmation, :role, :greeting
  belongs_to :user
  has_many :assignments

  # Scopes
  scope :alphabetical,  -> { order(:p1_last_name, :p1_first_name) }
  scope :search, ->(term) { where('p1_first_name LIKE ? OR p1_last_name LIKE ?', "#{term}%", "#{term}%") }

  # Validations
  validates_presence_of :p1_first_name, :p1_last_name
  validates_format_of :phone_number, with: /\A(\d{10}|\(?\d{3}\)?[-. ]\d{3}[-.]\d{4})\z/, message: "should be 10 digits (area code needed) and delimited with dashes only"
  validates_format_of :email, with: /\A[\w]([^@\s,;]+)@(([\w-]+\.)+(com|edu|org|net|gov|mil|biz|info))\z/i, message: "is not a valid format"

  validates_numericality_of :open_beds, only_integer: true, greater_than_or_equal_to: 0

  FAMILYSTYLE = ['Traditional', 'Therapeutic', 'Respite'] 

  # Callbacks
  before_save    -> { strip_nondigits_from(:phone_number) }
  before_update :deactive_user_if_parent_inactive
  before_destroy -> { cannot_destroy_object() }

  def proper_name
    "#{p1_first_name} #{p1_last_name}"
  end


  private
  def deactive_user_if_parent_inactive
    if !self.active && !self.user.nil?
      self.user.active = false
      self.user.save
    end
  end
end

app/controllers/parents_controller.rb
class ParentsController < ApplicationController
    before_action :set_parent, only: [:show, :edit, :update, :toggle_active_parent]
    before_action :check_login, only: [:show, :edit, :update, :index]
    authorize_resource
  
    def index
      @active_parents = Parent.active.paginate(page: params[:page]).per_page(15)
      @inactive_parents = Parent.inactive.paginate(page: params[:page]).per_page(15)
    end
  
    def new
      @parent = Parent.new
    end
  
    def create
      @parent = Parent.new(parent_params)
      @user = User.new(user_params)
      @user.role = "parent"
      if !@user.save
        @parent.valid?
        render action: 'new'
      else
        @parent.user_id = @user.id
        if @parent.save
          if !current_user.nil?
            flash[:notice] = "#{@parent.p1_first_name} #{@parent.p1_last_name} was added to the system."
            redirect_to parents_path
          else
            flash[:notice] = "Please login to access #{@parent.p1_first_name} #{@parent.p1_last_name}'s account."
            redirect_to login_path
          end 
        else
          render action: 'new'
        end
      end 
    end
  
  
    def edit
    end
  
    def show
      @parent = Parent.find(params[:id])
      @unique_assigned_categories = Category.joins(items: :assignments).where(assignments: { parent_id: @parent.id }).distinct
      # Fetch the unique item count by category
      @unique_item_count_by_category = Category.joins(items: :assignments)
                                                .where(assignments: { parent_id: @parent.id })
                                                .select('categories.id, COUNT(DISTINCT items.id) as unique_item_count')
                                                .group('categories.id')
                                                .index_by(&:id)
                                                .transform_values(&:unique_item_count)

      # Fetch the list of categories with incomplete assignments
      @categories_with_incomplete_assignments = Category.joins(items: :assignments)
                                                        .where(assignments: { parent_id: @parent.id, completion: false })
                                                        .distinct

    end
  
    def update
      if @parent.update_attributes(parent_params)
        redirect_to @parent, notice: "Successfully updated #{@parent.p1_last_name} Family."
      else
          render :action => 'edit'
      end
    end

    def toggle_active_parent
      if @parent.active
        @parent.update_attribute(:active, false)
        @parent.save

        flash[:notice] = "#{@parent.p1_last_name} family was made inactive"
        redirect_to parent_path(@parent)
      else
        @parent.update_attribute(:active, true)
        @parent.save

        flash[:notice] = "#{@parent.p1_last_name} family was made active"
        redirect_to parent_path(@parent)
      end
    end

    def assignments
      @assignments = Assignment.for_parent(@parent.id)
    end
  
    private
  
      def set_parent
        @parent = Parent.find(params[:id])
      end
  
      def parent_params
        params.require(:parent).permit(:p1_first_name, :p1_last_name, :p2_last_name, :p2_first_name, :email, :phone_number, :open_beds, :family_style, :active, :username, :password, :password_confirmation, :role)
      end
  
      def user_params
        params.require(:parent).permit(:active, :username, :password, :password_confirmation, :role)
      end

end

app/helpers/parents_helper.rb
module ParentsHelper
end

app/views/parents/_active_foster_parents.html.erb
<div class="card">
        <div class="card-content">
            <h4>Active Foster Parents</h4>

            <% if @active_parents.empty? %>
                <p>There are no inactive foster parents on file at this time.</p>
             
            <%else %>

                <table class = "striped highlight">
                    <thead>
                        <th>Foster Parent Names</th>
                        <th>Email</th>
                        <th>Assigned Forms</th>
                        <th>Incomplete</th>
                        
                    </thead>
                    <% for parent in @active_parents %>
                        <% if parent.active?%>
                            <tr>
                                <td><%= link_to "#{parent.p1_last_name}, #{parent.p1_first_name}", parent_path(parent)%></td>
                                <td><%= "#{parent.email}" %> </td>
                                <td><%= link_to "#{parent.assignments.size}", parent_assignments_path(parent) %> </td>
                                <td><%= "#{parent.assignments.incomplete.size}" %> </td>
                            </tr>
                        <% end %>
                    <% end %>
                </table>
            <%end%>
        </div>
    </div>

app/views/parents/_foster_parent_fields_data.html.erb
<%= f.input :p1_first_name, label_html: {class: 'active'}%>
<%= f.input :p1_last_name, label_html: { class: 'active' } %>
<%= f.input :p2_first_name, label_html: {class: 'active'}%>
<%= f.input :p2_last_name, label_html: { class: 'active' } %>
<%= f.input :email, label_html: { class: 'active' } %>
<%= f.input :phone_number, label_html: { class: 'active' } %>
<%= f.input :open_beds, label_html: { class: 'active' } %>
<%= f.input :family_style, collection: ['Traditional', 'Therapeutic', 'Respite'], include_blank: true %>
<%= f.hidden_field :role, :value => "parent" %>

app/views/parents/_inactive_foster_parents.html.erb
<div class="card">
        <div class="card-content">
            <h4>Inactive Foster Parents</h4>

            <% if @inactive_parents.empty? %>
                <p>There are no inactive foster parents on file at this time.</p>
             
            <%else %>

                <table class = "striped highlight">
                    <thead>
                        <th>Foster Parent Names</th>
                        <th>Email</th>
                        
                    </thead>
                    <% for parent in @inactive_parents %>
                        <% if !parent.active?%>
                            <tr>
                                <td><%= link_to "#{parent.p1_last_name}, #{parent.p1_first_name}", parent_path(parent)%></td>
                                <td><%= "#{parent.email}" %> </td>
                            </tr>
                        <% end %>
                    <% end %>
                </table>
            <%end%>
    </div>
</div>

app/views/parents/_parent_checklist.html.erb
<% if !current_user.nil? && current_user.role?(:case_worker) %>

    <div class="card">
        <div class="card-content">
        
            <h4><%= "#{@parent.p1_last_name}'s Checklist Categories"%> </h4>

                <% if @parent.assignments.empty? %>
                    <p>There are no active categories at this time because you have not been assigned anything to this parent.</p>
                
                <%else %>


                    <table class = "striped highlight">
                        <thead>
                            <th>Category Name</th>
                            <th>Number of Incomplete Assigned Items</th>
                            <th>Completion</th>
                        </thead>
                        
                        <% for category in @unique_assigned_categories %>
                            <% if category.active?%>
                                
                                <tr>
                                    <td><%= link_to "#{category.name}", item_show_path(category.id, parent_id: @parent.id)%></td>
                                    <td><%= "#{@unique_item_count_by_category[category.id]}" %> </td>
                                    <% if @categories_with_incomplete_assignments.exists?(category.id) %>
                                        <td style="color: #f04735"><%= "Incomplete"%></td>
                                    <% else %>
                                        <td style="color: #518458"><%= "Complete"%></td>
                                    <% end %>
                                </tr>
                            <% end %>
                        <% end %>
                    </table>
                <%end%>

        </div>
    </div>
 <%end%>

app/views/parents/_parent_data.html.erb
<div class="card">
    <div class="card-content">
        <h4><%= @parent.p1_last_name%> Family Unit</h4>

        <table class = "striped highlight">
            <thead>
                <th></th>
                <th>First Name</th>
                <th>Last Name</th>
            </thead>
                <tr>
                   <td><%= "Primary Parent"%></td>
                    <td><%= "#{@parent.p1_first_name}"%></td>
                    <td><%= "#{@parent.p1_last_name}" %></td>
                </tr>
                <% if @parent.p2_first_name != "" %>
                    <td><bold><%= "Secondary Parent"%></bold></td>
                    <td><%= "#{@parent.p2_first_name}"%></td>
                    <td><%= "#{@parent.p2_last_name}" %></td>
                <% end %>
        </table> <br><br>

        <% if @parent.active %>
            <b>Status: </b>Active Family<br><br>
        <% else %>
            <b>Status: </b>Inactive Family <br><br>
        <% end %>

        <b>Username:</b> <%= @parent.user.username%><br><br>

        <b>Phone Number:</b> <%= best_in_place @parent, :phone_number, as: :input, display_with: :number_to_phone %><br><br>

        <b>Email Address:</b> <%= best_in_place @parent, :email, as: :input %><br><br>

        <b>Open Beds:</b> <%= @parent.open_beds%><br><br>

        <b>Family Style:</b> <%= @parent.family_style%><br><br>

        <% if !current_user.nil? && current_user.role?(:case_worker) %>
            <% if @parent.active %>
                <%= link_to "Make Inactive", toggle_active_parent_path, method: :patch, class: 'waves-effect waves-light btn btn-alert'%>
            <% else %>
                <%= link_to "Make Active", toggle_active_parent_path, method: :patch, class: 'waves-effect waves-light btn btn-alert'%>
            <% end %>
        <% end%>

    </div>
</div>

app/views/parents/_user_fields.html.erb
<%= f.input :username, label_html: { class: 'active' } %>
<%= f.input :password, label_html: { class: 'active' } %>
<%= f.input :password_confirmation, label_html: { class: 'active' } %>

app/views/parents/edit.html.erb
<%= render partial: "partials/form_structure", locals: {object: @parent, 
                                                        type_of_form: "Edit Parent",
                                                        fields: "foster_parent_fields_data"} %>

app/views/parents/index.html.erb
<%= render partial: "partials/show2_structure", locals: {model_name: "parent", 
                                                         primary: "active_foster_parents", 
                                                         secondary: nil,
                                                         sidebar: "inactive_foster_parents"} %>

                                                         

app/views/parents/new.html.erb
<%= render partial: "partials/form2_structure", locals: {object: @parent, 
                                                        type_of_form: "New Foster Parent",
                                                        fields1: "foster_parent_fields_data",
                                                        section_2: "User Account",
                                                        fields2: "user_fields"} %>

app/views/parents/show.html.erb
<%= render partial: "partials/show_structure", locals: {model_name: "parent", 
                                                         object: @parent,
                                                         primary: "parent_data", 
                                                         secondary: nil,
                                                         sidebar: "parent_checklist"} %>