config/routes.rb
Rails.application.routes.draw do

  resources :sessions 
  # Semi-static page routes
   get 'home', to: 'home#index', as: :home
   get 'home/about', to: 'home#about', as: :about
   get 'home/contact', to: 'home#contact', as: :contact
   get 'home/privacy', to: 'home#privacy', as: :privacy
   get 'search', to: 'search#search', as: :search
 
   resources :users, only: [:edit, :index, :new, :create, :update]
   get 'users/new', to: 'users#new', as: :signup
   get 'user/edit', to: 'users#edit', as: :edit_current_user
   get 'login', to: 'sessions#new', as: :login
   get 'logout', to: 'sessions#destroy', as: :logout
 
   resources :categories
   resources :items, except: [:index] # in the future, items should be destroyed if there are no submissions attached

   resources :case_workers
   
   # access assignments and submissions for a given parent
   resources :parents do
    resources :assignments do
      resources :submissions
    end
   end

   resources :assignments
   resources :submissions

   #get 'parents/:id/assignments', to: 'assignment#index', as: :parent_assignments
   #get 'parents/:id/assignments/:a_id', to: 'assignment#show', as: :parent_assignment
   get 'items/:id/parent_show', to: 'items#parent_show', as: 'parent_show'
   get 'categories/:id/item_show', to: 'categories#item_show', as: :item_show

   patch 'categories/:id/toggle_active_category', to: 'categories#toggle_active_category', as: :toggle_active_category
   patch 'items/:id/toggle_active_item', to: 'items#toggle_active_item', as: :toggle_active_item
   patch 'parents/:id/toggle_active_parent', to: 'parents#toggle_active_parent', as: :toggle_active_parent

   root 'home#index'

  # Hello For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/category.rb
class Category < ApplicationRecord
    include AppHelpers::Activeable::InstanceMethods
    extend AppHelpers::Activeable::ClassMethods
    include AppHelpers::Deletions
    
    # Relationships
    has_many :items

    # Scopes
    scope :alphabetical,  -> { order(:name) }

    # Validations
    validates :name, presence: true, uniqueness: { case_sensitive: false }

    # Callbacks
    before_destroy do
        check_if_categories_have_items
        # if errors.present?
        #   @destroyable = false
        #   throw(:abort)
        # end
    end

    after_update :inactive_categories_have_inactive_items

    private
    def inactive_categories_have_inactive_items
        return true if self.active

        for item in self.items do
            item.make_inactive
        end
    end

    def check_if_categories_have_items
        unless self.items.empty?
            errors.add(:base, "This categories have current items associated, and therefore cannot be deleted.")
        end
    end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
    before_action :set_category, only: [:show, :edit, :update, :destroy, :toggle_active_category]
    before_action :set_unique_items_by_category_for_parent, only: [:index, :show], if: -> { current_user.role?(:parent) }
    before_action :check_login
    authorize_resource
  
    def index
      @active_categories = Category.active.paginate(page: params[:page]).per_page(15)
      @inactive_categories = Category.inactive.paginate(page: params[:page]).per_page(15)
      if current_user.role?(:parent)
        # all assignments that have been assigned to the user
        @assignments = Assignment.for_parent(current_user.parent.id).paginate(page: params[:page]).per_page(15)
        
        # a list of all the categories that she has been assigned to
        @unique_categories = @assignments.map { |assignment| assignment.item.category }.uniq
        
        # categories that have incomplete assignments, therefore the category is not complete
        @categories_with_incomplete_assignments = @unique_categories.select do |category|
          @assignments.any? { |assignment| assignment.item.category == category && !assignment.completion }
        end

      end
    end
  
    def new
      @category = Category.new
    end

    def show
      @category = Category.find(params[:id])
      @category_items = @category.items
    end

    def item_show
      @category = Category.find(params[:id])
      @parent = Parent.find(params[:parent_id])
      @assignments = Assignment.for_parent(@parent.id).paginate(page: params[:page]).per_page(15)

      @unique_item_count_by_category = Hash.new { |hash, key| hash[key] = Set.new }
      @unique_items_by_category = Hash.new { |hash, key| hash[key] = Set.new }

      @assignments.each do |assignment|
        category = assignment.item.category
        @unique_item_count_by_category[category].add(assignment.item)
        @unique_items_by_category[category].add(assignment.item)
      end

      @unique_item_count_by_category.each do |category, unique_items|
        @unique_item_count_by_category[category] = unique_items.size
      end
      
    end
  
    def create
      @category = Category.new(category_params)
      if @category.save
        flash[:notice] = "Successfully added #{@category.name} to the system."
        redirect_to categories_path
      else
        render action: 'new'
      end
    end

    def set_unique_items_by_category_for_parent
      @assignments = Assignment.for_parent(current_user.parent.id).paginate(page: params[:page]).per_page(15)

      # use a hash function to find unique items associated with each unique category that has been assigned to the user
      @unique_item_count_by_category = Hash.new { |hash, key| hash[key] = Set.new }
      @unique_items_by_category = Hash.new { |hash, key| hash[key] = Set.new }

      @assignments.each do |assignment|
        category = assignment.item.category
        @unique_item_count_by_category[category].add(assignment.item)
        @unique_items_by_category[category].add(assignment.item)
      end

      @unique_item_count_by_category.each do |category, unique_items|
        @unique_item_count_by_category[category] = unique_items.size
      end

    end

    def destroy
      @category = Category.find(params[:id])
    
      begin
        @category.destroy!
        flash[:success] = 'Category was successfully deleted.'
      rescue ActiveRecord::InvalidForeignKey => e
        flash[:error] = 'Cannot delete this Category: there are associated Items.'
      end
      
      redirect_to categories_path
    end
  
    def edit

    end
  
    def update
      if @category.update_attributes(category_params)
        flash[:notice] = "Successfully updated #{@category.name}."
        redirect_to categories_path
      else
        render action: 'edit'
      end
    end

    def toggle_active_category
      if @category.active
        @category.update_attribute(:active, false)
        @category.save

        flash[:notice] = "#{@category.name} was made inactive"
        redirect_to category_path(@category)
      else
        @category.update_attribute(:active, true)
        @category.save

        flash[:notice] = "#{@category.name} was made active"
        redirect_to category_path(@category)
      end
    end

    private
      def category_params
          params.require(:category).permit(:name, :active)
      end
  
      def set_category
          @category = Category.find(params[:id])
      end
  end
  

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_active_category_data.html.erb
<div class="card">
        <div class="card-content">
            <h4>Active Checklist Categories</h4>

            <% if @active_categories.empty? %>
                <p>There are no active categories at this time.</p>
             
            <%else %>
                <table class = "striped highlight">
                    <thead>
                        <th>Category Name</th>
                        <th>Number of Form Items</th>
                        <% if !current_user.nil? && current_user.role?(:parent) %>
                            <th>Completion</th>
                        <% end %>
                    </thead>
                    <% for category in @active_categories %>
                        <% if category.active?%>
                            <tr>
                                <td><%= link_to "#{category.name}", category_path(category)%></td>
                                <td><%= "#{category.items.size}" %> </td>
                                <% if !current_user.nil? && current_user.role?(:parent) %>
                                    <td><%= "Incomplete" %></td>
                                <% end %>
                            </tr>
                        <% end %>
                    <% end %>
                </table>
            <%end%>
        </div>
    </div>

app/views/categories/_category_by_assignments.html.erb
<div class="card">
        <div class="card-content">
            <h4><%= "Checklist Categories for #{current_user.parent.p1_last_name}, #{current_user.parent.p1_first_name}"%> </h4>

            <% if @assignments.empty? %>
                <p>There are no active categories at this time because you have not been assigned anything.</p>
             
            <%else %>


                <table class = "striped highlight">
                    <thead>
                        <th>Category Name</th>
                        <th>Number of Incomplete Assigned Items</th>
                        <th>Completion</th>
                    </thead>
                    
                    <% for category in @unique_categories %>
                        <% if category.active?%>
                            
                            <tr>
                                <td><%= link_to "#{category.name}", category_path(category)%></td>
                                <td><%= "#{@unique_item_count_by_category[category]}" %> </td>
                                <% if @categories_with_incomplete_assignments.include?(category)%>
                                    <td style="color: #f04735"><%= "Incomplete"%></td>
                                <% else %>
                                    <td style="color: #518458"><%= "Complete"%></td>
                                <% end %>
                            </tr>
                        <% end %>
                    <% end %>
                </table>
            <%end%>
        </div>
    </div>

app/views/categories/_category_data.html.erb
<% if !current_user.nil? && current_user.role?(:case_worker) %>
    <div class="card">
        <div class="card-content">
            <h4> <%= @category.name %> </h4>
            
                <% if @category.active %>
                    <b>Status:</b><p>Active Category</p><br>
                    <%= link_to "Make Inactive", toggle_active_category_path, method: :patch, class: 'waves-effect waves-light btn btn-alert'%>
                <% else %>
                    <b>Status:</b><p>Inactive Category (all file items under this category is also inactive)</p><br>
                    <%= link_to "Make Active", toggle_active_category_path, method: :patch, class: 'waves-effect waves-light btn btn-alert'%>
                <% end %>

        </div>
    </div>
<% end%>

app/views/categories/_category_fields.html.erb
<%= f.input :name, label_html: { class: 'active' } %>

app/views/categories/_inactive_category_data.html.erb
<div class="card">
        <div class="card-content">
            <h4>Inactive Checklist Categories</h4>

            <% if @inactive_categories.empty? %>
                <p>There are no inactive categories at this time.</p>
             
            <%else %>


                <table class = "striped highlight">
                    <thead>
                        <th>Category Name</th>
                        <th>Number of Form Items</th>
                    </thead>
                    <% for category in @inactive_categories %>
                        <% if !category.active%>
                            <tr>
                                <td><%= link_to "#{category.name}", category_path(category)%></td>
                                <td><%= "#{category.items.size}" %> </td>
                            </tr>
                        <% end %>
                    <% end %>
                </table>
            <%end%>

        </div>
    </div>

app/views/categories/_item_by_assignment_data.html.erb
<div class="card">
    <div class="card-content">
        <h4><%= "#{@category.name}" %> Files </h4>
        <table class = "striped highlight">
            <thead>
                <th>Section Items</th>
                <th>Completion</th>
                <th>Latest Submission</th>
            </thead>

            <% for item in @unique_items_by_category[@category] %>
                <tr>
                    <td><%= link_to "#{item.name}", item_path(item) %></td>
                    <% if item.assignments.exists?(completion: false)%>
                        <td style="color: #f04735"><%= "Incomplete"%></td>
                    <% else %>
                        <td style="color: #518458"><%= "Complete"%></td>
                    <% end %>

                    <% latest_submission = Submission.chronological.joins(:assignment).where(assignments: { item_id: item.id }).order(created_at: :desc).first %>
                    <% if !latest_submission.nil? && !latest_submission.file.nil?  %>
                        <td> <%= link_to "#{latest_submission.filename}", rails_blob_path(latest_submission.file, disposition: "attachment") %> </td>
                    <% else %>
                        <td>No linked files.</td> 
                    <% end %>
                </tr>
            <% end%>
        </table><br>
    </div>
</div>

app/views/categories/_item_data.html.erb
<% unless @category_items.empty? %>
    <% if !current_user.nil? && current_user.role?(:case_worker) %>
        <div class="card">
            <div class="card-content">
            <h4><%= "#{@category.name}" %> Files </h4>
                <table class = "striped highlight">
                    <thead>
                        <th>Section Items</th>
                        <th>File</th>
                        <th>Status</th>
                    </thead>

                    <% for item in @category_items %>
                        <tr>
                            <td><%= link_to "#{item.name}", item_path(item) %></td>
                            <% if !item.nil? && !item.file.nil? %>
                                <td> <%= link_to "#{item.filename}", rails_blob_path(item.file, disposition: "attachment") %> </td>
                            <% else %>
                                 <td>No linked files.</td> 
                             <% end %> 

                            <% if item.active %>
                                <td><p style="color: #518458">Active</p></td>
                            <% else %>
                                <td><p style="color: #f04735">Inactive</p></td>
                            <% end %>
                        </tr>
                    <% end%>
                </table><br>

                <% if can? :new, Item %>
                    <%= link_to "Add a New Item", new_item_path(category_id: @category.id), class: 'waves-effect waves-light btn btn-alert' %>
                <% end %>
            </div>
        </div>
    <% end%>
<% else%>
    <div class="card">
        <div class="card-content">
            <% if can? :new, Item %>
                <h4><%= "#{@category.name}" %> Files </h4>
                <p>There are currently no files associated with this category. Please add a file item below.</p><br>
                <%= link_to "Add a New Item", new_item_path(category_id: @category.id), class: 'waves-effect waves-light btn btn-alert' %>
            <% else %> 
                <h4><%= "#{@category.name}" %> Files </h4>
                <p>There are currently no files associated with this category. </p><br>
            <% end %>
        </div>
    </div>
<% end %>

app/views/categories/edit.html.erb
<%= render partial: "partials/form_structure", locals: {object: @category, 
                                                        type_of_form: "Edit Category",
                                                        fields: "category_fields"} %>

app/views/categories/index.html.erb
<% if !current_user.nil? && current_user.role?(:case_worker) %>
    <%= render partial: "partials/show2_structure", locals: {model_name: "category", 
                                                            primary: "active_category_data", 
                                                            secondary: "inactive_category_data",
                                                            sidebar: nil} %>
<% elsif !current_user.nil? && current_user.role?(:parent) %>
    <%= render partial: "partials/show2_structure", locals: {model_name: "category", 
                                                            primary: "category_by_assignments", 
                                                            secondary: nil,
                                                            sidebar: nil} %>
<% end %>

app/views/categories/item_show.html.erb
<div class="row">
  <div class="col s7">

        <div class="card">
            <div class="card-content">
                <h4><%= "#{@category.name}" %> Files </h4>
                <table class = "striped highlight">
                    <thead>
                        <th>Section Items</th>
                        <th>Completion</th>
                        <th>Latest Submission</th>
                    </thead>

                    <% for item in @unique_items_by_category[@category] %>
                        <tr>
                            <td><%= link_to "#{item.name}", parent_show_path(id: item.id, parent_id: @parent.id) %></td>
                            <% if item.assignments.exists?(completion: false)%>
                                <td style="color: #f04735"><%= "Incomplete"%></td>
                            <% else %>
                                <td style="color: #518458"><%= "Complete"%></td>
                            <% end %>

                            <% latest_submission = Submission.chronological.joins(:assignment).where(assignments: { item_id: item.id }).first %>
                            <% if !latest_submission.nil? && !latest_submission.file.nil?  %>
                                <td> <%= link_to "#{latest_submission.filename}", rails_blob_path(latest_submission.file, disposition: "attachment") %> </td>
                            <% else %>
                                <td>No linked files.</td> 
                            <% end %>
                        </tr>
                    <% end%>

                </table><br>
            </div>
        </div>
    </div>
</div>

app/views/categories/new.html.erb
<%= render partial: "partials/form_structure", locals: {object: @category,
                                                        type_of_form: "New Category",
                                                        fields: "category_fields"} %>

app/views/categories/show.html.erb
<% if !current_user.nil? && current_user.role?(:case_worker) %>
    <%= render partial: "partials/show_structure", locals: {model_name: "category", 
                                                            object: @category,
                                                            primary: "item_data", 
                                                            secondary: nil,
                                                            sidebar: "category_data"} %>
<% elsif !current_user.nil? && current_user.role?(:parent) %>
    <%= render partial: "partials/show_structure", locals: {model_name: "category", 
                                                            object: @category,
                                                            primary: "item_by_assignment_data", 
                                                            secondary: nil,
                                                            sidebar: nil} %>
<% end %>